app/controllers/blog.py
#!/usr/bin/env python
# -*-coding: utf-8 -*-
'''
@author: fanleehao
@contact: fanleehao@gmail.com
@file: blog.py
@time: 2018/10/1 17:50
@desc: blog博客展示页的单独模块蓝本
'''

from flask import render_template, Blueprint, redirect, url_for
from sqlalchemy import func  # 数据库操作中的一些库函数
import os

from app.models import db, User, Post, Comment, Tag, posts_tags
from app.forms import CommentForm, PostForm
from uuid import uuid4
import datetime


# 定义一个Blueprint类blog
blog_blueprint = Blueprint('blog', __name__, template_folder=os.path.join(os.path.pardir, 'templates', 'blog'), url_prefix='/blog')


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page, 10)
    recent, top_tags = slider_bar()
    return render_template('home.html', posts=posts, recent=recent, top_tags=top_tags)


@blog_blueprint.route('/post/<string:post_id>', methods=('GET', 'POST'))
def post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment(id=str(uuid4()), name=form.text.data)
        new_comment.text = form.text.data
        new_comment.date = datetime.datetime.now()
        new_comment.post_id = post_id
        db.session.add(new_comment)
        db.session.commit()

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = slider_bar()
    return render_template('post.html', post=post, tags=tags, comments=comments, form=form, recent=recent, top_tags=top_tags)


@blog_blueprint.route('/tag/<string:tag_name>')
def tag(tag_name):
    tag = Tag.query.filter_by(name=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = slider_bar()
    return render_template('tag.html', tag=tag, posts=posts, recent=recent, top_tags=top_tags)


@blog_blueprint.route('/user/<string:username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = slider_bar()
    return render_template('user.html', user=user, posts=posts, recent=recent, top_tags=top_tags)


@blog_blueprint.route('/new', methods=['GET', 'POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        newpost = Post(str(uuid4()), title=form.title.data)
        newpost.text = form.text.data
        newpost.publish_date = datetime.datetime.now()

        db.session.add(newpost)
        db.session.commit()
        return redirect(url_for('blog.home'))

    return render_template('new_post.html', form=form)


@blog_blueprint.route('/edit/<string:id>', methods=['GET', 'POST'])
def edit_post(id):
    """View function for edit_post."""

    post = Post.query.get_or_404(id)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        post.publish_date = datetime.datetime.now()

        # Update the post
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('blog.post', post_id=post.id))

    form.title.data = post.title
    form.text.data = post.text
    return render_template('edit_post.html', form=form, post=post)


def slider_bar():
    """
    desc: 侧边栏显示最近的5篇博文、每篇文章最多的5个标签
    :return:
    """
    # 最近5篇博文
    recent = db.session.query(Post).order_by(Post.publish_date.desc()).limit(5).all()
    # 标签
    top_tags = db.session.query(
        Tag, func.count(posts_tags.c.post_id).label('total')
    ).join(
        posts_tags
    ).group_by(Tag).order_by('total DESC').limit(5).all()
    return recent, top_tags

app/templates/blog/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,, initial-scale=1">
  <!-- Will be replace the page title -->
  <title>{% block title %}Home{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <!-- Macro: `render paginate` -->
  {% macro render_pagination(pagination, endpoint) %}
    <nav>
      <ul class="pagination">
        <li>
        {% if pagination.has_prev %}
          <a href="{{ url_for('blog.home', page=pagination.prev().page)
            }}" aria-label="Previous">
        {% else %}
          <a href="{{ url_for('blog.home', page=1) }}" aria-label="Previous">
        {% endif %}
            <span aria-label="true">&laquo;</span>
          </a>
        </li>
        {% for page in pagination.iter_pages() %}
          {% if page %}
            {% if page != pagination.page %}
              <li>
                <a href="{{ url_for(endpoint, page=page) }}">
                  {{ page }}
                </a>
              </li>
            {% else %}
              <li><a href="">{{ page }}</a></li>
            {% endif %}
          {% else %}
            <li><a>...</a></li>
          {% endif %}
        {% endfor %}
        <li>
          <a href="{{ url_for('blog.home', page=pagination.next().page )
            }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        <li>
      </ul>
    </nav>
  {% endmacro %}
</head>
<body>
  <div class="container">
    <div class="jumbotron">
      <!-- Replace the route function to URL: `/` -->
      <h1><a href="{{ url_for('blog.home')}} ">Fan's Blog</a></h1>
        <p>Welcome to the blog!</p>
    </div>
    {% block body %}
        Hello! Welcome
    {% endblock %}
  </div>
  <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

app/templates/blog/edit_post.html
{% extends "base.html" %}

{% block title %}Edit Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Edit the Post</h1>
  <form method="POST" action="{{ url_for('blog.edit_post', id=post.id) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control', value=post.title) }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

app/templates/blog/home.html
{% extends "base.html" %}
{% block title %}Fan's Blog{% endblock %}
<!--主页的集成-->
{% block body %}
    <div class="row">
        <div class="col-lg-9">
            <!--分页处理-->
            {% for post in posts.items %}
            <div class="row">
                <div class="col-lg-12">
                    <h1>{{ post.title }}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    {{ post.text | truncate(255) | safe }}
                    <!--读取更多的链接-->
                    <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-lg-3">
            <div class="row">
                <h5>Recent Posts</h5>
                <ul>
                    {% for post in recent %}
                    <li><a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a> </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="row">
                <h5>Popular Tags</h5>
                <ul>
                    {% for tag in top_tags %}
                    <li><a href="{{ url_for('blog.tag', tag_name=tag[0].name) }}">{{ tag[0].name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!--分页宏调用-->
        {{ render_pagination(posts, 'blog.home') }}
    </div>
{% endblock %}

app/templates/blog/new_post.html
{% block title %}New Post{% endblock %}
{% block body %}
<div class="row">
  <h1 class="text-center">Create A New Post</h1>
  <form method="POST" action="{{ url_for('blog.new_post') }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control') }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

app/templates/blog/post.html
{% extends "base.html"%}
{% block title %}{{ post.name }}{% endblock %}


{% block body %}
<h3>{{ post.title }}</h3>
{{ post.publish_date }}:
{{ post.text }}
<div class="row">
  <div class="col-lg-6">
    <p>Written By <a href="{{ url_for('blog.user', username=post.users.username)
      }}">{{ post.users.username }}</a> on {{ post.publish_date }}</p>
    <p>{{ post.text | safe }}</p>
  </div>
  <div class="column">
    <div class="col-lg-2">
      <a href="{{ url_for('blog.new_post') }}" class="btn btn-primary">New</a>
    </div>
  </div>
  <div class="column">
    <div class="col-lg-2">
      <a href="{{ url_for('blog.edit_post', id=post.id) }}" class="btn btn-primary">Edit</a>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <h3>New Comment:</h3>
  <!-- Set the form -->
  <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
    {{ form.hidden_tag() }}
    <div>
      <!-- Field: `name` label -->
      {{ form.name.label }}
      {% if form.name.errors %}
        {% for e in form.name.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.name(class_="form-control") }}
    </div>
    <div class="form-group">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(class_='form-control') }}
    </div>
    <input class="btn btn-primary" type="submit" value="Add Comment">
  </form>
</div>
{% endblock %}